### ISSUE TITLE
Mirror-Mobile App Communication: Request message types

### ISSUE THREAD

**Issue by BurakDmb** [ETU-ABC/ABC-Mirror#18]
Between the mobile application and the mirror software, we need to communicate in both directions and send-receive some information. 
Mostly we need to send information from mobile app to mirror and most of the requests will be in text form.

So, we need to add these type of messages to communicate between these two end points.

**For the mirror end point, we need to develop a module for supporting these type of messages.**

- [x] Get the list of available modules, returns the list of modules to show in the mobile app. #5
- [x] Set open/close commands for a module. #5
- [x] Set student number #4 
- [ ] Set location #3 
- [x] Set alarm #1 
- [ ] Deactive alarm #1
- [ ] Get alarm lists #1 
- [ ] Set email, password, hostname and port for email #6
- [ ] Set google calendar API key and select which calendars will be shown #2
